---
- name: Configure BIG-IP Nodes, Pools, and Virtual Servers
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../tmos_vars.yml

  vars:
    provider:
      server: "{{ tmos.address }}"
      server_port: 443
      user: "{{ tmos_user }}"
      password: "{{ tmos_password }}"
      validate_certs: false
      no_f5_teem: false

  tasks:
    - name: Render the iRule template
      template:
        src: "../templates/scale-irule.tcl.j2"
        dest: "/tmp/{{ irule_name }}.tcl"

    - name: Create the iRule
      f5networks.f5_modules.bigip_irule:
        provider: "{{  provider  }}"
        module: "ltm"
        name: "{{ irule_name }}"
        src: "/tmp/{{ irule_name }}.tcl"
        state: present

    - name: Fetch current rules for the virtual servers
      f5networks.f5_modules.bigip_virtual_server:
        provider: "{{ provider }}"
        name: "{{ item }}"
      register: vs_details
      loop: "{{ virtual_servers }}"
      async: 30
      poll: 0

    - name: Add the new rule to the existing list for each virtual server
      set_fact:
        updated_rules: "{{ vs.virtual_server.irules | default([]) + [irule_name] }}"
      loop: "{{ vs_details.results }}"
      loop_control:
        loop_var: vs

    - name: Bind the iRule to the virtual servers
      f5networks.f5_modules.bigip_virtual_server:
        provider: "{{ provider }}"
        name: "{{ item }}"
        irules: "{{ updated_rules }}"
      loop: "{{ virtual_servers }}"
      async: 30
      poll: 0
