---
- name: Migrate Applications
  hosts: cm_next
  gather_facts: false

- name: Backup BIG-IP as UCS
  import_playbook: cbip_getucs.yml

- name: Start Migration to BIG-IP Next
  import_playbook: next_migrate.yml
