---
- name: Detach iRule from virtual server
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../tmos_vars.yml

  tasks:
    - name: Fetch current rules for the virtual server
      f5networks.f5_modules.bigip_virtual_server:
        provider: "{{ provider }}"
        name: "{{ virtual_server_name }}"
      register: vs_details

    - name: Extract existing rules for the target virtual server
      set_fact:
        existing_rules: >-
          {{
            vs_details.virtual_server.irules | default([])
          }}

    - name: Remove the specified iRule from the list
      set_fact:
        updated_rules: "{{ existing_rules | difference([irule_name]) }}"

    - name: Bind the iRule to the virtual server
      f5networks.f5_modules.bigip_virtual_server:
        provider: "{{ provider }}"
        name: "{{ virtual_server_name }}"
        irules: "{{ updated_rules }}"
