---
- name: Main Playbook
  hosts: app
  become: true

- name: Setup TMOS virtual server routine
  import_playbook: tmos_setup.yml

- name: Create LTM routing policy
  import_playbook: tmos_ltm_routing_policy.yml

- name: Create Custom Monitor
  import_playbook: tmos_ltm_custom_monitor.yml

- name: Check TMOS BIG-IP is setup correctly and app is available
  import_playbook: tmos_ltm_ping.yml

