---
- name: AWAF Policy manage
  gather_facts: false
  hosts: cbip
  connection: httpapi

  vars_files:
    - cbip_vars.yml

  vars:
    ansible_host: "{{ provider.server }}"
    ansible_user: "{{ provider.user }}"
    ansible_httpapi_password: "{{ provider.password }}"
    ansible_httpapi_port: "{{ provider.server_port }}"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: "{{ provider.validate_certs }}"

  tasks:
    - name: Set ASM Policy to Blocking Mode
      f5networks.f5_bigip.bigip_awaf_policy:
        name: "{{ asm_policy_name }}"
        server_technologies:
          - Nginx
        partition: "Common"
        template: "POLICY_TEMPLATE_RAPID_DEPLOYMENT"
        enforcement_mode: "blocking"
        apply_policy: true
        state: "present"
