---
- name: Main Playbook
  hosts: app
  become: true

- name: Configure NGINX application
  import_playbook: app_install.yml

- name: Setup CBIP virtual server routine
  import_playbook: cbip_setup.yml

- name: Attach policy
  import_playbook: cbip_policy.yml

- name: Check BIG-IP is setup correctly and app is available
  import_playbook: cbip_app_ping.yml
