---
- name: Live Update and Push Signatures 
  hosts: localhost
  gather_facts: false

- name: Check Live Updates
  import_playbook: check_live_update.yml

- name: Push updates to next instances
  import_playbook: push_updates.yml

